---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    assert:
      that: true
  - name: Check Vector version
    ansible.builtin.shell: 
      cmd: 'vector --version'
    register: vector_version_status  
  - name: Check Vector data_dir
    ansible.builtin.shell: 
      cmd: 'grep ^data_dir /etc/vector/vector.toml'
  - name: Check release codes from Vector checking 
    assert:
      that: 
        - vector_version_status.rc == 0
